# **Linear Convolution**
Convolution is an operation performed on two functions, where one of the functions is flipped and shifted before being integrated over the range of the other function. In the context of signal processing, convolution is used to calculate the output of a linear time-invariant system given its input signal and impulse response. The result of the convolution operation is a new function that describes how the input signal is modified by the system.

In Python, convolution can be performed using the convolve function from the NumPy library. The convolve function takes two arrays as input and returns their convolution. For example, if x and h are two arrays containing the input signal and impulse response, respectively, then their convolution y can be computed using the following code:

In [2]:
import numpy as np

# Define input signal and impulse response
x = np.array([1, 2, 3])
h = np.array([0.5, 1, 0.5])

# Compute convolution
y = np.convolve(x, h)

print(y) # prints [0.5, 2, 3.5, 4, 1.5]

[0.5 2.  4.  4.  1.5]


Note that the length of the output array is **len(x) + len(h) - 1**. This is because the convolution operation involves shifting and summing the impulse response with the input signal at each time step, which causes the output to be longer than the input.

# **Circular Convolution**
Circular convolution is a type of convolution in which the signals are assumed to be periodic. Unlike linear convolution, circular convolution can handle periodic signals of finite length without producing any aliasing effects. It is often used in digital signal processing applications such as audio and image processing.

In circular convolution, the signals are multiplied in the frequency domain using the Discrete Fourier Transform (DFT), and then the inverse DFT is taken to obtain the circular convolution of the signals.

Here's an example of circular convolution in Python using the numpy library:

In [3]:
import numpy as np

# Define the signals
x = np.array([1, 2, 3, 4])
h = np.array([1, 1, 1])

# Compute the circular convolution using the DFT
N = len(x) + len(h) - 1
X = np.fft.fft(x, n=N)
H = np.fft.fft(h, n=N)
Y = X * H
y = np.fft.ifft(Y).real

# Print the result
print(y)

[1. 3. 6. 9. 7. 4.]


This code computes the circular convolution of the signals x and h. The `numpy.fft.fft` function is used to compute the DFT of the signals with zero-padding to the length of N, which is the sum of the lengths of x and h minus one. The DFT of each signal is multiplied element-wise to obtain the DFT of the circular convolution, and the `numpy.fft.ifft` function is used to compute the inverse DFT of the result. The real method is called to discard the imaginary parts of the result, since they should be zero for real-valued signals.

# **Cross-correlation**
Cross-correlation is a mathematical operation used to measure the similarity between two signals as a function of the time-lag applied to one of them. It is similar to the correlation operation but instead of comparing a signal with itself, it compares two different signals. Cross-correlation is used in many applications including signal processing, image processing, pattern recognition, and machine learning. In signal processing, cross-correlation is often used to detect the presence of a known signal within an unknown signal, to align two signals in time, and to estimate time delays between signals. In Python, cross-correlation can be computed using the numpy.correlate function.

In [4]:
import numpy as np
from scipy.signal import correlate

# Define two signals
x = np.array([1, 2, 3, 4, 5])
y = np.array([0, 1, 0, -1, 0])

# Compute the cross-correlation of x and y
corr_xy = correlate(x, y, mode='full')

# Print the result
print(corr_xy)

[ 0 -1 -2 -2 -2 -2  4  5  0]


In this example, we first define two signals x and y. We then use the correlate function from the scipy.signal module to compute the cross-correlation of x and y. The mode parameter is set to 'full', which means that the output will have length **len(x) + len(y) - 1**. The resulting cross-correlation is stored in the variable corr_xy, which is then printed.

# **Auto-correlation**
Auto-correlation is a mathematical operation that measures the similarity between a signal and a delayed version of itself. It is often used in signal processing to find patterns in a signal, detect periodicity, and estimate pitch.

In [5]:
import numpy as np

def auto_correlation(x):
    # Compute the auto-correlation of the signal
    return np.correlate(x, x, mode='same')

# Example usage
x = np.array([1, 2, 3, 4, 5])
r = auto_correlation(x)
print(r)

[26 40 55 40 26]


The output represents the auto-correlation of the input signal x. The first element of the output (r[0]) represents the auto-correlation at zero delay (i.e., the maximum correlation between the signal and itself), the second element (r[1]) represents the auto-correlation at a delay of one sample, and so on.